# Code starts here...
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(922, 893)
        MainWindow.setStyleSheet("#homepage{\n""background-color: #172F5F\n""}\n" "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(700, 800))
        self.tabWidget.setMaximumSize(QtCore.QSize(1900, 1000))
        self.tabWidget.setStyleSheet("background-color: rgb(148, 115, 250);")
        self.tabWidget.setObjectName("tabWidget")

        # Login page
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(183, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.loginframe = QtWidgets.QFrame(self.tab_4)
        self.loginframe.setMinimumSize(QtCore.QSize(500, 700))
        self.loginframe.setStyleSheet("background-color: #172F5F")
        self.loginframe.setObjectName("loginframe")
        self.formLayout_2 = QtWidgets.QFormLayout(self.loginframe)
        line_edit_stylesheet = """QLineEdit {
                        background-color: rgb(255, 255, 255); }
                    QLineEdit:hover {
                        border: 2px solid red; }
                    QLineEdit:focus {
                        border: 2px solid green; }"""
        self.formLayout_2.setObjectName("formLayout_2")
        self.title = QtWidgets.QLabel(self.loginframe)
        self.title.setMinimumSize(QtCore.QSize(0, 100))
        self.title.setStyleSheet("font-size:50px;\n"
"font-weight:bold;\n"
"margin-top:10px;\n"
"color: rgb(255, 255, 255);")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.title)
        self.l01 = QtWidgets.QLabel(self.loginframe)
        self.l01.setMinimumSize(QtCore.QSize(0, 80))
        self.l01.setStyleSheet("color: rgb(174, 44, 255);\n"
"\n"
"\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.l01.setObjectName("l01")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.l01)
        self.userid = QtWidgets.QLabel(self.loginframe)
        self.userid.setMinimumSize(QtCore.QSize(0, 80))
        self.userid.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.userid.setObjectName("userid")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.userid)
        self.lineEdit = QtWidgets.QLineEdit(self.loginframe)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit.setStyleSheet(line_edit_stylesheet)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.password = QtWidgets.QLabel(self.loginframe)
        self.password.setMinimumSize(QtCore.QSize(0, 80))
        self.password.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.password.setObjectName("password")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.password)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.loginframe)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_2.setStyleSheet(line_edit_stylesheet)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        # Common stylesheet for QPushButton
        button_stylesheet = """
                    QPushButton:hover {
                        border: 2px solid green;
                        color: green;
                        background-color: white;
                    }
                    QPushButton {
                        margin-top: 15px;
                        height: 50px;
                        width: 100px;
                        color: white;
                        background-color: green;
                        border-radius: 15px;
                        font-size: 18px;
                    }
                """
        self.rememberme = QtWidgets.QCheckBox(self.loginframe)
        self.rememberme.setMinimumSize(QtCore.QSize(0, 80))
        self.rememberme.setStyleSheet("\n"
"color:white;\n"
"font-size:18px;\n"
"margin-top:10px;")
        self.rememberme.setObjectName("rememberme")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.rememberme)
        self.login = QtWidgets.QPushButton(self.loginframe)
        self.login.setMinimumSize(QtCore.QSize(0, 50))
        self.login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login.setStyleSheet(button_stylesheet)
        self.login.setObjectName("login")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.login)
        self.gridLayout_2.addWidget(self.loginframe, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")

        # Homepage
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("jmilogo.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 800))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("hostel2.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("hostel.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("hostel 5.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("hostel3.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout.addWidget(self.frame_3)
        self.tabWidget.addTab(self.widget, "")

        # Hostel Registration
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 0, 1, 1)
        self.loginframe_3 = QtWidgets.QFrame(self.tab)
        self.loginframe_3.setMinimumSize(QtCore.QSize(500, 700))
        self.loginframe_3.setStyleSheet("background-color: #172F5F")
        self.loginframe_3.setObjectName("loginframe_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.loginframe_3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.title_1 = QtWidgets.QLabel(self.loginframe_3)
        self.title_1.setMinimumSize(QtCore.QSize(0, 100))
        self.title_1.setStyleSheet("font-size:50px;\n"
"font-weight:bold;\n"
"margin-top:10px;\n"
"color: rgb(255, 255, 255);")
        self.title_1.setAlignment(QtCore.Qt.AlignCenter)
        self.title_1.setObjectName("title_1")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.title_1)
        self.Hostelid_2 = QtWidgets.QLabel(self.loginframe_3)
        self.Hostelid_2.setMinimumSize(QtCore.QSize(0, 80))
        self.Hostelid_2.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.Hostelid_2.setObjectName("Hostelid_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Hostelid_2)
        self.Hostelidinp_2 = QtWidgets.QLineEdit(self.loginframe_3)
        self.Hostelidinp_2.setMinimumSize(QtCore.QSize(0, 50))
        self.Hostelidinp_2.setStyleSheet(line_edit_stylesheet)
        self.Hostelidinp_2.setObjectName("Hostelidinp_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Hostelidinp_2)
        self.Hostelname = QtWidgets.QLabel(self.loginframe_3)
        self.Hostelname.setMinimumSize(QtCore.QSize(0, 80))
        self.Hostelname.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.Hostelname.setObjectName("Hostelname")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Hostelname)
        self.Hostelnameinp = QtWidgets.QLineEdit(self.loginframe_3)
        self.Hostelnameinp.setMinimumSize(QtCore.QSize(0, 50))
        self.Hostelnameinp.setStyleSheet(line_edit_stylesheet)
        # self.Hostelnameinp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Hostelnameinp.setObjectName("Hostelnameinp")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Hostelnameinp)
        self.Savebtn = QtWidgets.QPushButton(self.loginframe_3)
        self.Savebtn.setMinimumSize(QtCore.QSize(0, 50))
        self.Savebtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Savebtn.setStyleSheet(button_stylesheet)
        self.Savebtn.setObjectName("Savebtn")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Savebtn)
        self.gridLayout_4.addWidget(self.loginframe_3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")

        # Room details
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 0, 1, 1)
        self.loginframe_4 = QtWidgets.QFrame(self.tab_3)
        self.loginframe_4.setMinimumSize(QtCore.QSize(500, 700))
        self.loginframe_4.setStyleSheet("background-color: #172F5F")
        self.loginframe_4.setObjectName("loginframe_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.loginframe_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.title_2 = QtWidgets.QLabel(self.loginframe_4)
        self.title_2.setMinimumSize(QtCore.QSize(0, 50))
        self.title_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.title_2.setStyleSheet("font-size:50px;\n"
"font-weight:bold;\n"
"margin-top:10px;\n"
"color: rgb(255, 255, 255);")
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.verticalLayout_4.addWidget(self.title_2)
        self.hostelid = QtWidgets.QLabel(self.loginframe_4)
        self.hostelid.setMinimumSize(QtCore.QSize(0, 40))
        self.hostelid.setMaximumSize(QtCore.QSize(16777215, 30))
        self.hostelid.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.hostelid.setObjectName("hostelid")
        self.verticalLayout_4.addWidget(self.hostelid)
        self.Hostelidinp = QtWidgets.QComboBox(self.loginframe_4)
        self.Hostelidinp.setMinimumSize(QtCore.QSize(0, 40))
        self.Hostelidinp.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Hostelidinp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Hostelidinp.setObjectName("Hostelidinp")
        self.verticalLayout_4.addWidget(self.Hostelidinp)
        self.Floor = QtWidgets.QLabel(self.loginframe_4)
        self.Floor.setMinimumSize(QtCore.QSize(0, 40))
        self.Floor.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Floor.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.Floor.setObjectName("Floor")
        self.verticalLayout_4.addWidget(self.Floor)
        self.Floorinp = QtWidgets.QLineEdit(self.loginframe_4)
        self.Floorinp.setMinimumSize(QtCore.QSize(0, 50))
        self.Floorinp.setMaximumSize(QtCore.QSize(16777213, 40))
        self.Floorinp.setStyleSheet(line_edit_stylesheet)
        self.Floorinp.setPlaceholderText("")
        self.Floorinp.setObjectName("Floorinp")
        self.verticalLayout_4.addWidget(self.Floorinp)
        self.Room = QtWidgets.QLabel(self.loginframe_4)
        self.Room.setMinimumSize(QtCore.QSize(0, 40))
        self.Room.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Room.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.Room.setObjectName("Room")
        self.verticalLayout_4.addWidget(self.Room)
        self.Roominp = QtWidgets.QLineEdit(self.loginframe_4)
        self.Roominp.setMinimumSize(QtCore.QSize(0, 50))
        self.Roominp.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Roominp.setStyleSheet(line_edit_stylesheet)
        self.Roominp.setPlaceholderText("")
        self.Roominp.setObjectName("Roominp")
        self.verticalLayout_4.addWidget(self.Roominp)
        self.Bed = QtWidgets.QLabel(self.loginframe_4)
        self.Bed.setMinimumSize(QtCore.QSize(0, 40))
        self.Bed.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Bed.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.Bed.setObjectName("Bed")
        self.verticalLayout_4.addWidget(self.Bed)
        self.Bedinp = QtWidgets.QLineEdit(self.loginframe_4)
        self.Bedinp.setMinimumSize(QtCore.QSize(0, 50))
        self.Bedinp.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Bedinp.setStyleSheet(line_edit_stylesheet)
        self.Bedinp.setPlaceholderText("")
        self.Bedinp.setObjectName("lineEdit_10")
        self.verticalLayout_4.addWidget(self.Bedinp)
        self.Submit = QtWidgets.QPushButton(self.loginframe_4)
        self.Submit.setMinimumSize(QtCore.QSize(0, 50))
        self.Submit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.Submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Submit.setStyleSheet(button_stylesheet)
        self.Submit.setObjectName("Submit")
        self.verticalLayout_4.addWidget(self.Submit)
        self.label_8 = QtWidgets.QLabel(self.loginframe_4)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.loginframe_4)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.gridLayout_3.addWidget(self.loginframe_4, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")

        # Student Registration
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.loginframe_5 = QtWidgets.QFrame(self.tab_2)
        self.loginframe_5.setMinimumSize(QtCore.QSize(500, 700))
        self.loginframe_5.setStyleSheet("background-color: #172F5F")
        self.loginframe_5.setObjectName("loginframe_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.loginframe_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.title_6 = QtWidgets.QLabel(self.loginframe_5)
        self.title_6.setMinimumSize(QtCore.QSize(0, 50))
        self.title_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.title_6.setStyleSheet("font-size:40px;\n"
"font-weight:bold;\n"
"margin-top:10px;\n"
"color: rgb(255, 255, 255);")
        self.title_6.setAlignment(QtCore.Qt.AlignCenter)
        self.title_6.setObjectName("title_6")
        self.verticalLayout_5.addWidget(self.title_6)
        self.userid_7 = QtWidgets.QLabel(self.loginframe_5)
        self.userid_7.setMinimumSize(QtCore.QSize(0, 40))
        self.userid_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.userid_7.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.userid_7.setObjectName("userid_7")
        self.verticalLayout_5.addWidget(self.userid_7)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.loginframe_5)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(25, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_3.setStyleSheet(line_edit_stylesheet)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_5.addWidget(self.lineEdit_3)
        self.userid_9 = QtWidgets.QLabel(self.loginframe_5)
        self.userid_9.setMinimumSize(QtCore.QSize(0, 40))
        self.userid_9.setMaximumSize(QtCore.QSize(16777215, 30))
        self.userid_9.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.userid_9.setObjectName("userid_9")
        self.verticalLayout_5.addWidget(self.userid_9)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.loginframe_5)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_4.setStyleSheet(line_edit_stylesheet)
        self.lineEdit_4.setObjectName("lineEdit_2")
        self.verticalLayout_5.addWidget(self.lineEdit_4)
        self.userid_8 = QtWidgets.QLabel(self.loginframe_5)
        self.userid_8.setMinimumSize(QtCore.QSize(0, 40))
        self.userid_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.userid_8.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.userid_8.setObjectName("userid_8")
        self.verticalLayout_5.addWidget(self.userid_8)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.loginframe_5)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_5.setStyleSheet(line_edit_stylesheet)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_5.addWidget(self.lineEdit_5)
        self.userid_10 = QtWidgets.QLabel(self.loginframe_5)
        self.userid_10.setMinimumSize(QtCore.QSize(0, 40))
        self.userid_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.userid_10.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.userid_10.setObjectName("userid_10")
        self.verticalLayout_5.addWidget(self.userid_10)
        self.Gender = QtWidgets.QComboBox(self.loginframe_5)
        self.Gender.setMinimumSize(QtCore.QSize(0, 25))
        self.Gender.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Gender.setEditable(True)
        self.Gender.setObjectName("Gender")
        self.Gender.addItem("")
        self.Gender.addItem("")
        self.Gender.addItem("")
        self.verticalLayout_5.addWidget(self.Gender)
        self.userid_11 = QtWidgets.QLabel(self.loginframe_5)
        self.userid_11.setMinimumSize(QtCore.QSize(0, 40))
        self.userid_11.setMaximumSize(QtCore.QSize(16777215, 30))
        self.userid_11.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.userid_11.setObjectName("userid_11")
        self.verticalLayout_5.addWidget(self.userid_11)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.loginframe_5)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_6.setStyleSheet(line_edit_stylesheet)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_5.addWidget(self.lineEdit_6)
        self.userid_12 = QtWidgets.QLabel(self.loginframe_5)
        self.userid_12.setMinimumSize(QtCore.QSize(0, 40))
        self.userid_12.setMaximumSize(QtCore.QSize(16777215, 30))
        self.userid_12.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.userid_12.setObjectName("userid_12")
        self.verticalLayout_5.addWidget(self.userid_12)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.loginframe_5)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_7.setStyleSheet(line_edit_stylesheet)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_5.addWidget(self.lineEdit_7)
        self.userid_13 = QtWidgets.QLabel(self.loginframe_5)
        self.userid_13.setMinimumSize(QtCore.QSize(0, 40))
        self.userid_13.setMaximumSize(QtCore.QSize(16777215, 30))
        self.userid_13.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.userid_13.setObjectName("userid_13")
        self.verticalLayout_5.addWidget(self.userid_13)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.loginframe_5)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_8.setStyleSheet(line_edit_stylesheet)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_5.addWidget(self.lineEdit_8)
        self.userid_14 = QtWidgets.QLabel(self.loginframe_5)
        self.userid_14.setMinimumSize(QtCore.QSize(0, 40))
        self.userid_14.setMaximumSize(QtCore.QSize(16777215, 30))
        self.userid_14.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.userid_14.setObjectName("userid_14")
        self.verticalLayout_5.addWidget(self.userid_14)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.loginframe_5)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_9.setStyleSheet(line_edit_stylesheet)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_5.addWidget(self.lineEdit_9)
        self.userid_15 = QtWidgets.QLabel(self.loginframe_5)
        self.userid_15.setMinimumSize(QtCore.QSize(0, 40))
        self.userid_15.setMaximumSize(QtCore.QSize(16777215, 30))
        self.userid_15.setStyleSheet("\n"
"color:white;\n"
"font-size:20px;\n"
"margin-top:10px;")
        self.userid_15.setObjectName("userid_15")
        self.verticalLayout_5.addWidget(self.userid_15)
        self.dateEdit = QtWidgets.QDateEdit(self.loginframe_5)
        self.dateEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.dateEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2050, 12, 31), QtCore.QTime(23, 59, 59)))
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_5.addWidget(self.dateEdit)
        self.submitbtn = QtWidgets.QPushButton(self.loginframe_5)
        self.submitbtn.setMinimumSize(QtCore.QSize(0, 50))
        self.submitbtn.setMaximumSize(QtCore.QSize(16777215, 60))
        self.submitbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitbtn.setStyleSheet(button_stylesheet)
        self.submitbtn.setObjectName("submitbtn")
        self.verticalLayout_5.addWidget(self.submitbtn)
        self.gridLayout_5.addWidget(self.loginframe_5, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")

        # Student Selection Ui
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(self.tab_5)
        self.frame.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-radius:12px;\n"
"background-color: #172F5F")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.student_selection_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.student_selection_label.setFont(font)
        self.student_selection_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.student_selection_label.setAlignment(QtCore.Qt.AlignCenter)
        self.student_selection_label.setObjectName("student_selection_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.student_selection_label)
        self.registration_year_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.registration_year_label.setFont(font)
        self.registration_year_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.registration_year_label.setObjectName("registration_year_label")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.registration_year_label)
        self.refresh_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.refresh_btn.sizePolicy().hasHeightForWidth())
        self.refresh_btn.setSizePolicy(sizePolicy)
        self.refresh_btn.setMinimumSize(QtCore.QSize(100, 50))
        self.refresh_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.refresh_btn.setFont(font)
        self.refresh_btn.setStyleSheet(button_stylesheet)
        self.refresh_btn.setObjectName("refresh_btn")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.refresh_btn)
        self.selected_student_label = QtWidgets.QLabel(self.frame)
        self.selected_student_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.selected_student_label.setObjectName("selected_student_label")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.selected_student_label)
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setTabletTracking(False)
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setColumnWidth(0, 200)
        self.tableWidget.setColumnWidth(1, 200)
        self.tableWidget.setColumnWidth(2, 200)
        self.tableWidget.setColumnWidth(3, 200)
        self.tableWidget.setColumnWidth(4, 200)
        self.tableWidget.setColumnWidth(5, 200)
        self.tableWidget.setColumnWidth(6, 200)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.tableWidget)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setMinimumSize(QtCore.QSize(50, 50))
        self.comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setEditable(True)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.comboBox.setCurrentIndex(-1)

        # Student Allocation Ui
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.std_allocation_frame = QtWidgets.QFrame(self.tab_6)
        self.std_allocation_frame.setMinimumSize(QtCore.QSize(0, 800))
        self.std_allocation_frame.setStyleSheet("#std_allocation_frame {\n"
"background-color: #172F5F;\n"
"padding:30px;\n"
"}\n"
"\n"
"QLabel {\n"
"color:white;\n"
"font-size:18px;\n"
"margin-top:10px;\n"
"}\n"
"\n"
"#title_3 {\n"
"font-size:50px;\n"
"font-weight:bold;\n"
"margin-bottom:50px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"height:25px;\n"
"margin-top:10px;\n"
"font-size:15px;\n"
"border:2px solid gray;\n"
"padding: 5px 15px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"border:2px solid red;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"border:2px solid green;\n"
"}\n"
"\n"
"#submitbtn1 {\n"
"margin-top:25px;\n"
"height:40px;\n"
"width:100px;\n"
"color:white;\n"
"background-color:green;\n"
"border-radius:15px;\n"
"font-size:18px;\n"
"}\n"
"#submitbtn1:hover {\n"
"border: 2px solid green;\n"
"color: green;\n"
"background-color:white;\n"
"}")
        self.std_allocation_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.std_allocation_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.std_allocation_frame.setObjectName("std_allocation_frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.std_allocation_frame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.spinBox = QtWidgets.QSpinBox(self.std_allocation_frame)
        self.spinBox.setStyleSheet("height:25px;\n"
"margin-top:10px;\n"
"font-size:15px;\n"
"border:2px solid gray;\n"
"padding: 5px 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(4)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_7.addWidget(self.spinBox, 10, 0, 2, 3)
        self.room = QtWidgets.QComboBox(self.std_allocation_frame)
        self.room.setMinimumSize(QtCore.QSize(0, 30))
        self.room.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.room.setEditable(False)
        self.room.setMaxVisibleItems(20)
        self.room.setFrame(False)
        self.room.setModelColumn(0)
        self.room.setObjectName("room")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.room.addItem("")
        self.gridLayout_7.addWidget(self.room, 8, 0, 1, 3)
        self.name_2 = QtWidgets.QLabel(self.std_allocation_frame)
        self.name_2.setStyleSheet("background-color: #172F5F;")
        self.name_2.setObjectName("name_2")
        self.gridLayout_7.addWidget(self.name_2, 3, 0, 1, 2)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.std_allocation_frame)
        self.lineEdit_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_7.addWidget(self.lineEdit_15, 2, 0, 1, 3)
        self.select_yr = QtWidgets.QLabel(self.std_allocation_frame)
        self.select_yr.setStyleSheet("background-color: #172F5F;")
        self.select_yr.setObjectName("select_yr")
        self.gridLayout_7.addWidget(self.select_yr, 12, 0, 1, 3)
        self.name_3 = QtWidgets.QLabel(self.std_allocation_frame)
        self.name_3.setStyleSheet("background-color: #172F5F;")
        self.name_3.setObjectName("name_3")
        self.gridLayout_7.addWidget(self.name_3, 5, 0, 1, 2)
        self.lineEdit_16 = QtWidgets.QComboBox(self.std_allocation_frame)
        self.lineEdit_16.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_7.addWidget(self.lineEdit_16, 4, 0, 1, 3)
        self.name = QtWidgets.QLabel(self.std_allocation_frame)
        self.name.setStyleSheet("background-color: #172F5F;\n"
"")
        self.name.setObjectName("name")
        self.gridLayout_7.addWidget(self.name, 1, 0, 1, 3)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.std_allocation_frame)
        self.dateEdit_2.setStyleSheet("height:25px;\n"
"margin-top:10px;\n"
"font-size:15px;\n"
"border:2px solid gray;\n"
"padding: 5px 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.dateEdit_2.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2030, 12, 28), QtCore.QTime(23, 59, 59)))
        self.dateEdit_2.setMaximumDate(QtCore.QDate(2030, 12, 28))
        self.dateEdit_2.setMinimumDate(QtCore.QDate(2000, 9, 14))
        self.dateEdit_2.setTimeSpec(QtCore.Qt.TimeZone)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_7.addWidget(self.dateEdit_2, 13, 0, 1, 3)
        self.allot_bed = QtWidgets.QLabel(self.std_allocation_frame)
        self.allot_bed.setStyleSheet("background-color: #172F5F;")
        self.allot_bed.setObjectName("allot_bed")
        self.gridLayout_7.addWidget(self.allot_bed, 9, 0, 1, 2)
        self.name_4 = QtWidgets.QLabel(self.std_allocation_frame)
        self.name_4.setStyleSheet("background-color: #172F5F;")
        self.name_4.setObjectName("name_4")
        self.gridLayout_7.addWidget(self.name_4, 7, 0, 1, 3)
        self.floor = QtWidgets.QComboBox(self.std_allocation_frame)
        self.floor.setMinimumSize(QtCore.QSize(0, 30))
        self.floor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.floor.setObjectName("floor")
        self.floor.addItem("")
        self.floor.addItem("")
        self.floor.addItem("")
        self.floor.addItem("")
        self.floor.addItem("")
        self.floor.addItem("")
        self.floor.addItem("")
        self.floor.addItem("")
        self.gridLayout_7.addWidget(self.floor, 6, 0, 1, 3)
        self.submitbtn1 = QtWidgets.QPushButton(self.std_allocation_frame)
        self.submitbtn1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitbtn1.setStyleSheet("")
        self.submitbtn1.setObjectName("submitbtn1")
        self.gridLayout_7.addWidget(self.submitbtn1, 14, 0, 1, 2)
        self.title_3 = QtWidgets.QLabel(self.std_allocation_frame)
        self.title_3.setStyleSheet("background-color: #172F5F;")
        self.title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.title_3.setObjectName("title_3")
        self.gridLayout_7.addWidget(self.title_3, 0, 1, 1, 2)
        self.gridLayout_8.addWidget(self.std_allocation_frame, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem9, 0, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem10, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")

        # Menu UI
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menu = QtWidgets.QMenuBar(MainWindow)
        self.menu.setGeometry(QtCore.QRect(0, 0, 922, 39))
        self.menu.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 255);")
        self.menu.setObjectName("menu")
        self.menu1 = QtWidgets.QMenu(self.menu)
        self.menu1.setObjectName("menu1")
        self.menu2 = QtWidgets.QMenu(self.menu)
        self.menu2.setObjectName("menu2")
        self.menu3 = QtWidgets.QMenu(self.menu)
        self.menu3.setObjectName("menu3")
        self.menu4 = QtWidgets.QMenu(self.menu)
        self.menu4.setObjectName("menu4")
        self.menu5 = QtWidgets.QMenu(self.menu)
        self.menu5.setObjectName("menu5")
        MainWindow.setMenuBar(self.menu)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu1a = QtWidgets.QAction(MainWindow)
        self.menu1a.setObjectName("menu1a")
        self.menu1b = QtWidgets.QAction(MainWindow)
        self.menu1b.setObjectName("menu1b")
        self.menu2a = QtWidgets.QAction(MainWindow)
        self.menu2a.setObjectName("menu2a")
        self.menu2b = QtWidgets.QAction(MainWindow)
        self.menu2b.setObjectName("menu2b")
        self.menu2c = QtWidgets.QAction(MainWindow)
        self.menu2c.setObjectName("menu2c")
        self.menu3a = QtWidgets.QAction(MainWindow)
        self.menu3a.setObjectName("menu3a")
        self.menu3b = QtWidgets.QAction(MainWindow)
        self.menu3b.setObjectName("menu3b")
        # self.menu1.addAction(self.menu1a)
        # self.menu1.addAction(self.menu1b)

        self.menu2.addAction(self.menu2b)
        self.menu2.addAction(self.menu2a)
        self.menu2.addAction(self.menu2c)
        self.menu3.addAction(self.menu3a)
        self.menu3.addAction(self.menu3b)
        self.menu.addAction(self.menu1.menuAction())
        self.menu.addAction(self.menu2.menuAction())
        self.menu.addAction(self.menu3.menuAction())
        self.menu.addAction(self.menu4.menuAction())
        self.menu.addAction(self.menu5.menuAction())
        self.menu4a = QtWidgets.QAction(MainWindow)
        self.menu4a.setObjectName("menu4a")
        self.menu4.addAction(self.menu4a)
        self.menu4b = QtWidgets.QAction(MainWindow)
        self.menu4b.setObjectName("menu4b")
        self.menu4.addAction(self.menu4b)

        # Set Indexes
        self.retranslateUi(MainWindow)
        # self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(-1)
        self.room.setCurrentIndex(0)
        self.lineEdit_16.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        # Login Page Ui
        self.title.setText(_translate("MainWindow", "Admin Login"))
        self.l01.setText(_translate("MainWindow", "                         Enter User Id and Password"))
        self.userid.setText(_translate("MainWindow", "User Id "))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "👤 user id"))
        self.password.setText(_translate("MainWindow", "Password"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "🔐 password"))
        self.rememberme.setText(_translate("MainWindow", "Remember me "))
        self.login.setText(_translate("MainWindow", "Log In"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "login"))

        # Homepage
        self.label_7.setText(_translate("MainWindow", "Welcome To JMI Hostel Management System"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "homepage"))

        # Hostel Registration
        self.title_1.setText(_translate("MainWindow", "Hostel Registration"))
        self.Hostelid_2.setText(_translate("MainWindow", "Hostel ID"))
        self.Hostelidinp_2.setPlaceholderText(_translate("MainWindow", "Enter Hostel Id"))
        self.Hostelname.setText(_translate("MainWindow", "Hostel Name"))
        self.Hostelnameinp.setPlaceholderText(_translate("MainWindow", " Enter Hostel Name"))
        self.Savebtn.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "hostel"))

        # Room Details
        self.title_2.setText(_translate("MainWindow", "Room Details"))
        self.hostelid.setText(_translate("MainWindow", "Hostel"))
        self.Floor.setText(_translate("MainWindow", "No Of Floors"))
        self.Room.setText(_translate("MainWindow", "No Of Rooms In Each Floor"))
        self.Bed.setText(_translate("MainWindow", "No Of Beds In Each Room"))
        self.Submit.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "room"))

        # Student Registration
        self.title_6.setText(_translate("MainWindow", "Student Registration"))
        self.userid_7.setText(_translate("MainWindow", "Student Id"))
        self.userid_9.setText(_translate("MainWindow", "Student Name"))
        self.userid_8.setText(_translate("MainWindow", "Father\'s Name"))
        self.userid_10.setText(_translate("MainWindow", "Gender"))
        self.Gender.setItemText(0, _translate("MainWindow", "Male"))
        self.Gender.setItemText(1, _translate("MainWindow", "Female"))
        self.Gender.setItemText(2, _translate("MainWindow", "Other"))
        self.userid_11.setText(_translate("MainWindow", "Email"))
        self.userid_12.setText(_translate("MainWindow", "Mobile No"))
        self.userid_13.setText(_translate("MainWindow", "Address"))
        self.userid_14.setText(_translate("MainWindow", "Last Year Percentage"))
        self.userid_15.setText(_translate("MainWindow", "Year"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.submitbtn.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "sregister"))

        # Student Selection
        self.student_selection_label.setText(_translate("MainWindow", "Student Selection"))
        self.registration_year_label.setText(_translate("MainWindow", "Registration Year"))
        self.refresh_btn.setText(_translate("MainWindow", "Submit"))
        self.selected_student_label.setText(_translate("MainWindow", "Selected Student"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Reg_No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Student_Id"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Student_Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Fathers_Name"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Year"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Check"))
        self.comboBox.setItemText(0, _translate("MainWindow", "2023"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2022"))
        self.comboBox.setItemText(2, _translate("MainWindow", "2021"))
        self.comboBox.setItemText(3, _translate("MainWindow", "2020"))
        self.comboBox.setItemText(4, _translate("MainWindow", "2019"))
        self.comboBox.setItemText(5, _translate("MainWindow", "2018"))
        self.comboBox.setItemText(6, _translate("MainWindow", "2017"))
        self.comboBox.setItemText(7, _translate("MainWindow", "2016"))
        self.comboBox.setItemText(8, _translate("MainWindow", "2015"))
        self.comboBox.setItemText(9, _translate("MainWindow", "2014"))
        self.comboBox.setItemText(10, _translate("MainWindow", "2013"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "sselection"))

        # Student Allocation
        self.room.setItemText(0, _translate("MainWindow", "00"))
        self.room.setItemText(1, _translate("MainWindow", "01"))
        self.room.setItemText(2, _translate("MainWindow", "02"))
        self.room.setItemText(3, _translate("MainWindow", "03"))
        self.room.setItemText(4, _translate("MainWindow", "04"))
        self.room.setItemText(5, _translate("MainWindow", "05"))
        self.room.setItemText(6, _translate("MainWindow", "06"))
        self.room.setItemText(7, _translate("MainWindow", "07"))
        self.room.setItemText(8, _translate("MainWindow", "08"))
        self.room.setItemText(9, _translate("MainWindow", "09"))
        self.room.setItemText(10, _translate("MainWindow", "10"))
        self.room.setItemText(11, _translate("MainWindow", "11"))
        self.room.setItemText(12, _translate("MainWindow", "12"))
        self.room.setItemText(13, _translate("MainWindow", "13"))
        self.room.setItemText(14, _translate("MainWindow", "14"))
        self.room.setItemText(15, _translate("MainWindow", "15"))
        self.name_2.setText(_translate("MainWindow", "Hostel "))
        self.lineEdit_15.setPlaceholderText(_translate("MainWindow", "👤 Student Id"))
        self.select_yr.setText(_translate("MainWindow", "Select year"))
        self.name_3.setText(_translate("MainWindow", "Floor No"))
        self.lineEdit_16.setPlaceholderText(_translate("MainWindow", " Hostel Id"))
        self.name.setText(_translate("MainWindow", "Search Student Name"))
        self.dateEdit_2.setDisplayFormat(_translate("MainWindow", "yyyy"))
        self.allot_bed.setText(_translate("MainWindow", "Allot bed"))
        self.name_4.setText(_translate("MainWindow", "Room No"))
        self.floor.setItemText(0, _translate("MainWindow", "0"))
        self.floor.setItemText(1, _translate("MainWindow", "1"))
        self.floor.setItemText(2, _translate("MainWindow", "2"))
        self.floor.setItemText(3, _translate("MainWindow", "3"))
        self.floor.setItemText(4, _translate("MainWindow", "4"))
        self.floor.setItemText(5, _translate("MainWindow", "5"))
        self.floor.setItemText(6, _translate("MainWindow", "6"))
        self.floor.setItemText(7, _translate("MainWindow", "7"))
        self.submitbtn1.setText(_translate("MainWindow", "Submit"))
        self.title_3.setText(_translate("MainWindow", "Student Allocation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "sallocation"))

        # Menu Bar
        self.menu1.setTitle(_translate("MainWindow", "Master"))
        self.menu2.setTitle(_translate("MainWindow", "Transaction"))
        self.menu3.setTitle(_translate("MainWindow", "Report"))
        self.menu4.setTitle(_translate("MainWindow", "Exit"))
        self.menu5.setTitle(_translate("MainWindow", "Cancel"))
        # self.menu1a.setText(_translate("MainWindow", "Hostel Registration"))
        # self.menu1b.setText(_translate("MainWindow", "Room Details"))
        self.menu2a.setText(_translate("MainWindow", "Student selection"))
        self.menu2b.setText(_translate("MainWindow", "Student Registration"))
        self.menu2c.setText(_translate("MainWindow", "Student Allocation"))
        self.menu3a.setText(_translate("MainWindow", "Hostel Report"))
        self.menu3b.setText(_translate("MainWindow", "Room Report"))
        self.menu4a.setText(_translate("MainWindow", "Logout"))
        self.menu4b.setText(_translate("MainWindow", "Exit"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
